// <auto-generated />
namespace ZerOneUniversityApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v1departmentstudentadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1departmentstudentadd));
        
        string IMigrationMetadata.Id
        {
            get { return "201802091122053_v1 department student add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
